BEGIN;

ALTER TABLE "PlayerVote"
  ADD COLUMN "goals" INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN "assists" INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN "yellowCards" INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN "redCards" INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN "ownGoals" INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN "penaltiesMissed" INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN "penaltiesSaved" INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN "cleanSheet" INTEGER NOT NULL DEFAULT 0;

ALTER TABLE "PlayerVote"
  DROP COLUMN "bonusPoints",
  DROP COLUMN "malusPoints";

COMMIT;
